name: Release Javadocs

on:
  push:
    branches: ["main"]
    paths:
      - "Lottery/javadocs/**"

jobs:
  Release_javadocs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          clean: true
          folder: Lottery/javadocs
          target-folder: javadoc
